---
title: "flat_sum_function.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.
-->

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# My function

```{r function-sum_function}
#' My Sum Function to Add Numbers
#' 
#' This function allows you to add 2 to any number inputted into the function
#' 
#' @param x is a numeric value
#'
#' @return this returns x + 2
#' 
#' @export
#'
#' @examples
#' 
sum_function <- function(x) {

if(isFALSE(is.numeric(x)))  {
  stop("The argument `x` must be a number")
}
  
  result <- x + 2
  return(result)
  
}
```

```{r development-sum_function}

# Here I test and develop the function

sum_function <- function(x) {

if(isFALSE(is.numeric(x)))  {
  stop("The argument `x` must be a number")
}
  
  result <- x + 2
  return(result)
  
}
```


```{r examples-sum_function}

# An input of 2 should be 4 
sum_function(x = 2)

#An input of 4 should be 6
sum_function(x = 4)

#An input of 10 should be 12
sum_function(x = 10)

```

```{r tests-sum_function}
test_that("sum_function works", {
  expect_equal(
    object = sum_function(x = 2),
    expected = 4
  )
  
  expect_error(
    object = sum_function(x = "three"),
    regexp = "The argument `x` must be a number"
  )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_sum_function.Rmd", vignette_name = "Sum Function")
```
