# WARNING - Generated by {fusen} from /dev/flat_minus_function.Rmd: do not edit by hand

test_that("minus_function works", {
  expect_equal(
    object = minus_function(x = 5),
    expected = 2
  )
  
  expect_error(
    object = minus_function(x = "5"),
    regexp = ("The argument `x` must be a number.")
  )
})
