# WARNING - Generated by {fusen} from /dev/flat_sum_function.Rmd: do not edit by hand

test_that("sum_function works", {
  expect_equal(
    object = sum_function(x = 2),
    expected = 4
  )
  
  expect_error(
    object = sum_function(x = "three"),
    regexp = "The argument `x` must be a number"
  )
})
