# WARNING - Generated by {fusen} from /dev/flat_times_two_function.Rmd: do not edit by hand

test_that("times_two_function works", {
  expect_equal(
    object = times_two_function(x = 10),
    expected = 20
  )
  
  expect_error(
    object = times_two_function(x = "10"),
    regexp = ("'x' must be of numeric class")
  )
})
