# WARNING - Generated by {fusen} from /dev/flat_minus_function.Rmd: do not edit by hand

#' My Minus Function
#'
#'This function subtracts 3 numbers from an inputted value
#'
#' @param x is a numeric value
#'
#' @return this returns x - 3
#' 
#' @export
#'
#' @examples
#' # An input of 5 should be 2
#' minus_function(5)
#' 
#' # An input of 7 should be 4
#' minus_function(7)
#' 
#' # An input of 10 should be 7
#' minus_function(10)
minus_function <- function(x) {
  if(isFALSE(is.numeric(x))) {
    stop("The argument `x` must be a number.")
  }
  
  result <- (x - 3)
  return(result)
  
}
