# WARNING - Generated by {fusen} from /dev/flat_sum_function.Rmd: do not edit by hand

#' My Sum Function to Add Numbers
#' 
#' This function allows you to add 2 to any number inputted into the function
#' 
#' @param x is a numeric value
#'
#' @return this returns x + 2
#' 
#' @export
#'
#' @examples
#' 
#' 
#' # An input of 2 should be 4 
#' sum_function(x = 2)
#' 
#' #An input of 4 should be 6
#' sum_function(x = 4)
#' 
#' #An input of 10 should be 12
#' sum_function(x = 10)
#' 
sum_function <- function(x) {

if(isFALSE(is.numeric(x)))  {
  stop("The argument `x` must be a number")
}
  
  result <- x + 2
  return(result)
  
}
