# WARNING - Generated by {fusen} from /dev/flat_times_two_function.Rmd: do not edit by hand

#' My double function
#' 
#' This function doubles any numeric value input into the function.
#' 
#' @param x is a numeric value
#' 
#' @return this returns x * 2
#' 
#' @export
#' 
#' @examples
#' 
#' 
#' # Output must be 10
#' times_two_function(5)
#' 
#' #Output must be 24
#' times_two_function(12)
#' 
#' #Output must be 48
#' times_two_function(24)
times_two_function <- function(x) {
  if(is.numeric(x)) {
    message("Good input!")
  } else {
    stop("'x' must be of numeric class")
  }
  
result <- x * 2
return(result)
}
